#!/bin/sh

current_dir_=$(dirname "$0")
. "${current_dir_}/functions"

mozrepl_port_=4242
current_profile_="Global"
url_="$@"

##############################################################################

# Checking if Firefox Global is already opened by checking MozRepl port

do_notify_short "Opening ${url_} with ${current_profile_} profile"

is_local_port_open ${mozrepl_port_} && (
    cmd_="switchToTabHavingURI('${url_}', true)"
    echo "${cmd_}" | nc -q 0 localhost ${mozrepl_port_} >/dev/null
) || (
    /m/opt/firefox-beta/firefox "$@" -ProfileManager & disown
)
