#!/usr/bin/env ruby

#
# Get current monitors information with format
# - First line is the number of connected monitors
# - From the second line: <name> <best-mode> <best-rate>
#

monitors = `xrandr | grep " connected" | cut -d" " -f1`.split("\n")
awk_command = "awk '{ if (line > 0) { print; line-- } } /^PATTERN/ { line = 1 } '"

puts monitors.length
monitors.each do |output|
  mode_n_rate = `xrandr | #{awk_command.sub("PATTERN", output)}`.sub("*", "")
                                                                .sub("+", "")
                                                                .split
  mode = mode_n_rate.first
  rate = mode_n_rate.last
  puts "#{output} #{mode} #{rate}"
end
