#!/usr/bin/env ruby

# git@github.com:schacon/hg-git.git
# git+ssh://git@github.com/schacon/hg-git.git

if !ARGV[0]
  puts """Usage: github_repo_to_ssh \"<Github SSH repository>\"

Convert Github style SSH repository to universal Git SSH style repository.

Example:

$ github_repo_to_ssh \"git@github.com:schacon/hg-git.git\"
git+ssh://git@github.com/schacon/hg-git.git
"""
  exit -1
end

github_repo = ARGV[0]

puts "git+ssh://#{github_repo.sub(':', '/').sub('git///', '')}"
