#!/bin/bash

read -r -d '' USAGE <<'EOF'
Usage
    intel-adjust-brightness --get       :: Get current brightness
    intel-adjust-brightness --get-max   :: Get maximum brightness supported by
                                           your card
    intel-adjust-brightness --increase  :: Increase brightness by 1 level
    intel-adjust-brightness --decrease  :: Decrease brightness by 1 level
    intel-adjust-brightness --help      :: Print this help

NOTE: you will need NOPASSWD: /usr/bin/tee in your /etc/sudoers for this
command to function.
EOF

function path_exists {
    ls "$1" &>/dev/null
}

MAX_BRIGHTNESS_PATH=/sys/class/backlight/acpi_video0/max_brightness
CURRENT_BRIGHTNESS_PATH=/sys/class/backlight/acpi_video0/brightness

path_exists ${MAX_BRIGHTNESS_PATH} || (
    echo "> You need ${MAX_BRIGHTNESS_PATH} for this program to function." >&2
    exit 1
)

function current_brightness {
    echo $(cat ${CURRENT_BRIGHTNESS_PATH})
}

function max_brightness {
    echo $(cat ${MAX_BRIGHTNESS_PATH})
}

function increase_brightness {
    NEW_BRIGHTNESS=$(echo $(current_brightness)+1 | bc)
    [[ ${NEW_BRIGHTNESS} -gt $(max_brightness) ]] || (
        sudo tee ${CURRENT_BRIGHTNESS_PATH} <<< ${NEW_BRIGHTNESS} >/dev/null
    )
    echo $(current_brightness)/$(max_brightness)
}

function decrease_brightness {
    NEW_BRIGHTNESS=$(echo $(current_brightness)-1 | bc)
    [[ ${NEW_BRIGHTNESS} -gt 0 ]] && (
        sudo tee ${CURRENT_BRIGHTNESS_PATH} <<< ${NEW_BRIGHTNESS} >/dev/null
    )
    echo $(current_brightness)/$(max_brightness)
}


case $1 in
    "-h" | "--help")
        show_usage
        ;;
    "-i" | "--increase")
        increase_brightness
        ;;
    "-d" | "--decrease")
        decrease_brightness
        ;;
    "-g" | "--get-max")
        max_brightness
        ;;
    "--get")
        current_brightness
        ;;
    *)
        echo "${USAGE}" >&2
        ;;
esac
