= `bin`
:toc: auto
:toclevels: 4
:numbered:
:icons: font
:source-highlighter: pygments
:pygments-css: class

A collection of my scripts.  I wrote most but not all of them.  Many of them
are written in http://doc.cat-v.org/plan_9/4th_edition/papers/rc[Rc shell],
for Bourne-or-Bash-compatible shell suffers from many design flaws, making it
difficult to maintain.

This document is written in literate programming style.  To generate scripts
and documentation, you need latest stable version of
https://github.com/cmpitg/ulquikit[Ulquikit].  You could also clone the repo
and start using it yourself.

I have just rewritten this README since today (Dec 5^th, 2015).  In the next
couple of days, I will include all installation scripts and detailed
instructions to make the setup as painless as possible.

== Requirements

For everything to function correctly, you need:

* https://github.com/9fans/plan9port[Plan 9 from User Space] (Plan9port)
* GNU Emacs 24+

Some scripts depend on others.  It's best to fulfill the requirements for all
of them.

== Notes

My environment is unusual:

* `${HOME}/Data` is either a symlink or a mount point, pointing to all
  configuration and data belonging to the tools I use.
+
If you have a separated `${HOME}`, you just need to create the `Data`
directory.
+
The main reasons why I don't use separated partition for `${HOME}` is because:
1) `${HOME}` itself is extremely inconsistent and cluttered (`.config`,
`.local`, dot files, capticalized names vs. lower-case names, etc.); and 2) I
use serveral distros, where each piece of software is slightly different in
versions, thus different in configuration.
+
In my main system, `/home/cmpitg/Data` is a symlink to `/mnt/home/cmpitg`,
whereas `/mnt/home` is a mount point.

* `${HOME}/Data/Mount-Points` contains a collection of shortcuts to various
  directories, and `/m` is its symlink into `/`.
+
I like to separate the original directories from their shortcuts and to make
things globally visible.  Some might argue that this is a serious security
flaw.  I disagree.  Private things should be kept away.  Put your `.ssh`
should never stay in `/m`.

* `/m/${USER}` is a symlink back to `${HOME}/Data`, so all symlinks in `/m`
  can utilize `/m/${USER}` itself.
+
Symlinks are very useful if used appropriately (examples include the
https://nixos.org/nix/[Nix package manager]).  For me, using `/m/src` is much
more effective and unified than `~/src` for what `~` depends on what your
current user is.  I could also re-symlink `/m/src` whenever I want with very
simple commands.
+
[source]
----
✗ l /m
lrwxrwxrwx 1 root root 30 Nov 28 20:24 /m -> /home/cmpitg/Data/Mount-Points/

✗ l /m/
total 12K
drwxr-xr-x  4 cmpitg cmpitg 4.0K Nov 28 22:04 ./
drwxr-xr-x 29 cmpitg cmpitg 4.0K Dec  1 23:44 ../
dr-xr-xr-x  1 cmpitg cmpitg    0 Jan  1  1970 9p-fonts/
drwxr-xr-x  2 cmpitg cmpitg 4.0K Nov 23 22:23 acme/
lrwxrwxrwx  1 cmpitg cmpitg   13 Nov 28 22:01 bin -> /m/cmpitg/Bin/
lrwxrwxrwx  1 cmpitg cmpitg   17 Nov 28 20:22 cmpitg -> /home/cmpitg/Data/
lrwxrwxrwx  1 cmpitg cmpitg   16 Feb 15  2015 config -> /m/cmpitg/Config/
lrwxrwxrwx  1 cmpitg cmpitg   13 Nov 28 22:02 opt -> /m/cmpitg/Opt/
lrwxrwxrwx  1 cmpitg cmpitg   17 Aug  3  2014 scratch -> /m/cmpitg/Scratch/
lrwxrwxrwx  1 cmpitg cmpitg   18 Nov 28 22:04 src -> /m/cmpitg/Src/
lrwxrwxrwx  1 cmpitg cmpitg   15 Feb 15  2015 talks -> /m/cmpitg/Talks/
lrwxrwxrwx  1 cmpitg cmpitg   17 Aug  3  2014 toolbox -> /m/cmpitg/Toolbox/
lrwxrwxrwx  1 cmpitg cmpitg   22 Aug  3  2014 virtenvs -> /m/cmpitg/Virtual-Envs/
lrwxrwxrwx  1 cmpitg cmpitg   18 Nov 28 20:35 www -> /m/cmpitg/WWW/
----
+
Most directories should speak for themselves.  Exceptions include:
+
** `/m/9p-fonts`: mounted by Plan9port's `fontsrv` to serve fonts, and
** `/m/acme`: file system interface of Acme.

== Installation

For installation of Plan9port, please refer to
https://github.com/9fans/plan9port[its original documentation].

To be written...

''''

== Contents

=== `9` - sets up the environment for Plan9port applications

* Starts and mounts 9p font server to `/m/9p-fonts`
* Creates temporary directory: `/tmp/9-${USER}`
* And executes a command in a Plan9port environment in `${PLAN9}/bin`.  If
  `PLAN9` variable is not set, it is set to `/m/opt/plan9port` by default.

.file::9
[source,sh,linenums]
----
#!/bin/sh

##
## Sets up the environment for Plan9port applications:
## * Starts plumber and font server
## * Runs the corresponding program
##

export TEMP9=/tmp/9-${USER}
export PLAN9=/m/opt/plan9port
export PATH=${PLAN9}/bin:${PATH}

export SHELL=rc
export TERM=9term
export font='/m/9p-fonts/Droid Sans Mono/11a/font'

mkdir -p ${TEMP9}

running-p plumber || plumber
running-p fontsrv || \
	nohup fontsrv \
		-m /m/9p-fonts \
		>${TEMP9}/fontsrv.out \
		2>${TEMP9}/fontsrv.err &

exec ${PLAN9}/bin/9 "$@"

----

=== `9-term` - runs Plan9port terminal emulator within a 9 environment

.file::9-term
[source,sh,linenums]
----
#!/usr/bin/env rc

#
# Starts 9term within an Rc environment.
#

9term $*

----

=== `acme` - runs Plan9port Acme with `9`

Font can be chosen by setting the `font` environment variable.  By default, it
is set to `/m/9p-fonts/Droid Sans Mono/11a/font`.

.file::acme
[source,sh,linenums]
----
#!/usr/bin/env rc

#
# Starts Acme with font specified by variable `font'.  By default, use Droid
# Sans Mono.
#

if (~ $font '') {
	font='/m/9p-fonts/Droid Sans Mono/11a/font'
}

acme -a \
	-m /m/acme \
	-f $font $* $toolbox

----

=== `cat-which <executable>` - `cat $(which executable)`

Finds full path to executable and displays the content.

.file::cat-which
[source,sh,linenums]
----
#!/bin/sh

#
# Finds full path to executable and displays the content.
#

exec_="$@"

if $(which "${exec_}" >/dev/null); then
	cat $(which "${exec_}")
else
	echo "${exec_} not found" >&2
fi

----

=== `check-broken-symlinks [path1] [path2] [...]`

.file::check-broken-symlinks
[source,sh,linenums]
----
#!/bin/sh

#
# Checks for broken symlinks.
#

for file_ in "$@" ; do
	if [ -L "${file_}" ]; then
		if readlink -q "${file_}" >/dev/null ; then
			echo "Good link: ${file_}"
		else
			echo "${file_}: bad link" >/dev/stderr
		fi
	else
		echo "${file_} is not a symlink"
	fi
done

----

=== `buildapp-cmpitg` - builds Common Lisp standalone executable

With https://github.com/xach[@xach's]
http://www.xach.com/lisp/buildapp/[Buildapp].  This script takes
https://common-lisp.net/project/asdf/[ASDF] manifest file from `manifest`
environment variable.  By default, `manifest` is set to
`/m/config/common-lisp/sbcl-quicklisp-manifest.txt`.

.file::buildapp-cmpitg
[source,sh,linenums]
----
#!/usr/bin/env rc

if (~ $manifest '') {
	manifest='/m/config/common-lisp/sbcl-quicklisp-manifest.txt'
}

buildapp --manifest-file $manifest \
	--load /m/Toolbox/SBCL/sbcl-cmpitg-base.lisp \
	$*

----

=== `chmod-default [dir]` - fixes permissions

`chmod` a directory recursively, 755 for files and 644 for directories.  By
default, `dir` is current working directory.

.file::chmod-default
[source,sh,linenums]
----
#!/bin/sh

test -z "$1" && dir_="." || dir_="$1"

find "${dir_}" -type d -print0 | xargs -0 chmod 0755
find "${dir_}" -type f -print0 | xargs -0 chmod 0644

----

=== `cl-write-manifest` - writes ASDF manifest file

Writes
https://common-lisp.net/project/asia/asia.html#_how_to_create_project_manifest_database[ASDF
manifest] file to a location, set by environment variable `manifest`.  By
default, `manifest` is set to
`/m/config/common-lisp/sbcl-quicklisp-manifest.txt`.

.file::cl-write-manifest
[source,sh,linenums]
----
#!/usr/bin/env rc

if (~ $manifest '') {
	manifest='/m/config/common-lisp/sbcl-quicklisp-manifest.txt'
}

echo Writing manifest file $manifest

sbcl-cmpitg --no-userinit --no-sysinit --non-interactive \
    --eval '(ql:write-asdf-manifest-file "'^$manifest^'")'

----

=== `clojure-repl` - starts Clojure REPL with http://leiningen.org/[Lein]

Starts a Clojure REPL in a directory, set by the `clojure_root` environment
variable.  By default, `clojure_root` is set to `${HOME}/test/clojure/main`.

.file::clojure-repl
[source,sh,linenums]
----
#!/usr/bin/env rc

if (~ $clojure_root '') {
	clojure_root=$home/test/clojure/main
}

pushd .
cd $clojure_root
lein repl $@
popd

----

=== `comment-code` - comments code, read from stdin

Comments code by prefixing them with line comment character string by the
first argument passed in this script.  By default, prefix code with `# `.

.file::comment-code
[source,sh,linenums]
----
#!/usr/bin/env rc

#
# Comments a piece of code.
#

if (~ $1 '') {
	comment_char='#'
}
if not {
	comment_char=$1
}

prefix $comment_char^' '

----

=== `config-keymap-altgr` - keyboard layout: Programmer Dvorak + Right Alt as AltGr + Ctrl-Alt swapped + CapsLock-Escape swapped

.file::config-keymap-altgr
[source,sh,linenums]
----
#!/bin/bash

test -z "${DISPLAY}" && exit 0

setxkbmap us -variant dvp -option lv3:ralt_alt
xmodmap <( cat <<EOF
! -*- mode: xmodmap-generic -*-
! No modifier map for mod5
clear mod5
add mod4 = Super_R

! Swap Escape and Capslock
remove Lock = Caps_Lock
add Lock = Escape
keysym Caps_Lock = Escape
keysym Escape = Caps_Lock

! Swap left Control and Alt
remove control = Control_L
remove mod1 = Alt_L
remove mod1 = Meta_L
keysym Control_L = Meta_L
keysym Control_L = Alt_L
keysym Alt_L = Control_L
add mod1 = Meta_L
add mod1 = Alt_L
add control = Control_L

! Swap right Control and Alt
remove control = Control_R
remove mod1 = Alt_R
keysym Control_R = Alt_R
keysym Alt_R = Control_R

add control = Control_R

! Add AltGr to Alt_R
add mod5 = Alt_R

EOF
)

----

=== `config-keymap-cmpitg` - keyboard layout: Programmer Dvorak + Ctrl-Alt swapped + CapsLock-Escape swapped

.file::config-keymap-cmpitg
[source,sh,linenums]
----
#!/bin/bash

test -z "${DISPLAY}" && exit 0

##############################################################################

do-notify-short "Setting specialized keylayout"
newline
setxkbmap us -variant dvp -option lv3:ralt_alt
if (test -e ~/.Xmodmap); then
	xmodmap ~/.Xmodmap
else
	xmodmap <( cat <<EOF
! -*- mode: xmodmap-generic -*-
! No modifier map for mod5
clear mod5
add mod4 = Super_R

! Swap Escape and Capslock
remove Lock = Caps_Lock
add Lock = Escape
keysym Caps_Lock = Escape
keysym Escape = Caps_Lock

! Swap left Control and Alt
remove control = Control_L
remove mod1 = Alt_L
remove mod1 = Meta_L
keysym Control_L = Meta_L
keysym Control_L = Alt_L
keysym Alt_L = Control_L
add mod1 = Meta_L
add mod1 = Alt_L
add control = Control_L

! Swap right Control and Alt
remove control = Control_R
remove mod1 = Alt_R
keysym Control_R = Alt_R
keysym Alt_R = Control_R
add mod1 = Alt_R
add control = Control_R

EOF
)
fi

config-logitech-trackball-marble-righty
# config-logitech-trackball-marble-lefty
config-logitech-g300-mouse
config-logitech-g502-mouse
config-lenovo-mouse

config-touchpad
config-touchpad

----

=== `config-keymap-steam` - keyboard layout: Programmer Dvorak without AltGr

Because Steam doesn't work with swapped modifiers.

.file::config-keymap-steam
[source,sh,linenums]
----
#!/bin/bash

test -z "${DISPLAY}" && exit 0

do-notify-short "Setting keyboard layout for Steam"
newline
setxkbmap us -variant dvp -option lv3:ralt_alt

config-logitech-g502-mouse

----

== License

Unless clearly stated, do whatever you want with them.  If you like me, buy me
good Vietnamese coffee or something stronger :-).

== Description

* `prefix [text]` - Reads text from stdin an prefix all lines with
  `text`. `text` is set to `# ` by default. In Rc shell.

* `i3-exec-command` - Execute an i3 command in [i3 window
  manager](http://i3wm.org/), in SH.

* `i3-switch-window` - Task switcher for
  [i3 window manager](http://i3wm.org/), in Python using `dzen`.

* `i3-move-to-workspace` - Move a window to a workspace in i3 window manager,
  in SH.

* `i3-to-workspace` - Switch to a workspace in i3 window manager, in SH.

* `i3-rename-workspace` - Rename a workspace in i3 window manager, in SH.

* `update-sbcl` - Check and update [SBCL](http://www.sbcl.org/), in Ruby.

* `rename-urt-demos` - Rename Urban Terror 4.1 demo files (upcase, reformat
  for better timestamp and map), in Python.

* `get-monitors` - Get `output mode rate` for all active monitors using
  `xrandr`, in Ruby.

* `github-repo-to-ssh` - Convert `git@` protocol to `git+ssh` which Mercurial
  understands, in Ruby.

* `set-default-monitor-config` - Basic multihead, in Ruby.

* `du-this` - Get disk usage for all files and directories residing in the
  current directory and sort them in descending order, in SH.

* `monitor-off` - Turn off monitor, in SH.

* `show-cpu-temp` - Show my laptap's 2 CPUs temperature, in SH.

* `run-ibus-daemon` - Run/restart iBus daemon, with Xim support, in SH.

* `run-xiki` - Fresh start Xiki (due to a bug at startup, Xiki needs to
  restart after the first run), in SH.

* `run-zsnes` - Run Zsnes emulator, in SH.

* `git-rm-orphaned` - Remove deleted files from Git cache, in SH.

* `firefox-beta` - Run Firefox beta, in SH.

* `firefox-beta-new-instance` - Run new instance of Firefox beta (Firefox is
  called with `no-remote`), in SH.

* `python-print-site-packages-path` - Print Python site packages path, in SH.

* `intel-adjust-brightness` - Adjust brightness with shell script, requires
  `ALL=NOPASSWD: /usr/bin/tee` in your `/etc/sudoers` (edited by `visudo`), in
  SH.

* `virtualenv-symlink` - Symlink Python
  [virtualenv](https://virtualenv.pypa.io/en/latest/), in SH.

* `count-monitors` - Count number of connected monitors, in SH.

* `extract-audio` - Extract from a video file, creating the same file name
  with appropriate extension, in SH with FFmpeg.

* `update-openjdk-8-font-patched` - Update OpenJDK 8 with font rendering patch
  from PPA
  [no1wantdthisname](https://launchpad.net/~no1wantdthisname/+archive/ubuntu/openjdk-fontfix),
  in [Rc shell](http://plan9.bell-labs.com/sys/doc/rc.html).

* `local-port-open-p <port>` - Check if a local port is open, returning 0 if it is
  and 1 otherwise, in SH.

* `sbcl-cmpitg-slime <port> ...` - Start a SBCL Slime on a bunch of ports with
  Tmux; if called with no argument, use port 4005, in Rc shell.

* `format-text` (env var: `column`) - Format text with
  [par](http://www.nicemice.net/par/); column width is set by `column`
  environment variable; by default `column` is `78`, in Rc shell.

* `emacs-format-text` - Format text with Emacs (batch mode) width column width
  78 (TODO: customizable), in Rc shell, requires Emacs.
