= `bin`
:toc: auto
:toclevels: 4
:numbered:
:experimental: true
:icons: font
:source-highlighter: pygments
:pygments-css: class

A collection of my scripts.  I wrote most but not all of them.  Many of them
are written in http://doc.cat-v.org/plan_9/4th_edition/papers/rc[Rc shell],
for Bourne-or-Bash-compatible shell suffers from many design flaws, making it
difficult to maintain.

This document is written in literate programming style.  To generate scripts
and documentation, you need latest stable version of
https://github.com/cmpitg/ulquikit[Ulquikit].  You could also clone the repo
and start using it yourself.

I have just rewritten this README since today (Dec 5^th, 2015).  In the next
couple of days, I will include all installation scripts and detailed
instructions to make the setup as painless as possible.

== Requirements

For everything to function correctly, you need:

* https://github.com/9fans/plan9port[Plan 9 from User Space] (Plan9port)
* GNU Emacs 24+

Some scripts depend on others.  It's best to fulfill the requirements for all
of them.

== Notes

My environment is unusual:

* `${HOME}/Data` is either a symlink or a mount point, pointing to all
  configuration and data belonging to the tools I use.
+
If you have a separated `${HOME}`, you just need to create the `Data`
directory.
+
The main reasons why I don't use separated partition for `${HOME}` is because:
1) `${HOME}` itself is extremely inconsistent and cluttered (`.config`,
`.local`, dot files, capticalized names vs. lower-case names, etc.); and 2) I
use serveral distros, where each piece of software is slightly different in
versions, thus different in configuration.
+
In my main system, `/home/cmpitg/Data` is a symlink to `/mnt/home/cmpitg`,
whereas `/mnt/home` is a mount point.

* `${HOME}/Data/Mount-Points` contains a collection of shortcuts to various
  directories, and `/m` is its symlink into `/`.
+
I like to separate the original directories from their shortcuts and to make
things globally visible.  Some might argue that this is a serious security
flaw.  I disagree.  Private things should be kept away.  Your `.ssh` should
never stay in `/m`.

* `/m/${USER}` is a symlink back to `${HOME}/Data`, so all symlinks in `/m`
  can utilize `/m/${USER}` itself.
+
Symlinks are very useful if used appropriately (examples include the
https://nixos.org/nix/[Nix package manager]).  For me, using `/m/src` is much
more effective and unified than `~/src` for what `~` depends on what your
current user is.  I could also re-symlink `/m/src` whenever I want with very
simple commands.
+
[source]
----
✗ l /m
lrwxrwxrwx 1 root root 30 Nov 28 20:24 /m -> /home/cmpitg/Data/Mount-Points/

✗ l /m/
total 12K
drwxr-xr-x  4 cmpitg cmpitg 4.0K Nov 28 22:04 ./
drwxr-xr-x 29 cmpitg cmpitg 4.0K Dec  1 23:44 ../
dr-xr-xr-x  1 cmpitg cmpitg    0 Jan  1  1970 9p-fonts/
drwxr-xr-x  2 cmpitg cmpitg 4.0K Nov 23 22:23 acme/
lrwxrwxrwx  1 cmpitg cmpitg   13 Nov 28 22:01 bin -> /m/cmpitg/Bin/
lrwxrwxrwx  1 cmpitg cmpitg   17 Nov 28 20:22 cmpitg -> /home/cmpitg/Data/
lrwxrwxrwx  1 cmpitg cmpitg   16 Feb 15  2015 config -> /m/cmpitg/Config/
lrwxrwxrwx  1 cmpitg cmpitg   13 Nov 28 22:02 opt -> /m/cmpitg/Opt/
lrwxrwxrwx  1 cmpitg cmpitg   17 Aug  3  2014 scratch -> /m/cmpitg/Scratch/
lrwxrwxrwx  1 cmpitg cmpitg   18 Nov 28 22:04 src -> /m/cmpitg/Src/
lrwxrwxrwx  1 cmpitg cmpitg   15 Feb 15  2015 talks -> /m/cmpitg/Talks/
lrwxrwxrwx  1 cmpitg cmpitg   17 Aug  3  2014 toolbox -> /m/cmpitg/Toolbox/
lrwxrwxrwx  1 cmpitg cmpitg   22 Aug  3  2014 virtenvs -> /m/cmpitg/Virtual-Envs/
lrwxrwxrwx  1 cmpitg cmpitg   18 Nov 28 20:35 www -> /m/cmpitg/WWW/
----
+
Most directories should speak for themselves.  Exceptions include:
+
** `/m/9p-fonts`: mounted by Plan9port's `fontsrv` to serve fonts, and
** `/m/acme`: file system interface of Acme.

== Installation

For installation of Plan9port, please refer to
https://github.com/9fans/plan9port[its original documentation].

To be written...

''''

== Contents

=== `9` - sets up the environment for Plan9port applications

* Starts and mounts 9p font server to `/m/9p-fonts`
* Creates temporary directory: `/tmp/9-${USER}`
* And executes a command in a Plan9port environment in `${PLAN9}/bin`.  If
  `PLAN9` variable is not set, it is set to `/m/opt/plan9port` by default.

.file::9
[source,sh]
----
#!/bin/bash

##
## Sets up the environment for Plan9port applications:
## * Starts plumber and font server
## * Runs the corresponding program
##

export TEMP9=/tmp/9-${USER}
export PLAN9=/m/opt/plan9port
export PATH=${PLAN9}/bin:${PATH}

export SHELL=rc
export TERM=9term
export font='/m/9p-fonts/Droid Sans Mono/11a/font'

mkdir -p ${TEMP9}

running-p plumber || plumber
running-p fontsrv || \
	nohup fontsrv \
		-m /m/9p-fonts \
		>${TEMP9}/fontsrv.out \
		2>${TEMP9}/fontsrv.err &

exec ${PLAN9}/bin/9 "$@"

----

=== `9-term` - runs Plan9port terminal emulator within a 9 environment

.file::9-term
[source,sh]
----
#!/usr/bin/env rc

#
# Starts 9term within an Rc environment.
#

9term $*

----

=== `acme` - runs Plan9port Acme with `9`

Font can be chosen by setting the `font` environment variable.  By default, it
is set to `/m/9p-fonts/Droid Sans Mono/11a/font`.

.file::acme
[source,sh]
----
#!/usr/bin/env rc

#
# Starts Acme with font specified by variable `font'.  By default, use Droid
# Sans Mono.
#

if (~ $font '') {
	font='/m/9p-fonts/Droid Sans Mono/11a/font'
}

acme -a \
	-m /m/acme \
	-f $font $* $toolbox

----

=== `cat-which <executable>` - `cat $(which executable)`

.file::cat-which
[source,sh]
----
#!/bin/bash

#
# Finds full path executables and displays the content.
#


for exec_ in "$@"; do
	if $(which "${exec_}" &>/dev/null); then
		cat $(which "${exec_}")
	else
		echo "${exec_} not found" >&2
	fi
done

----

=== `check-broken-symlinks [path1] [path2] [...]`

.file::check-broken-symlinks
[source,sh]
----
#!/bin/bash

#
# Checks for broken symlinks.
#

for file_ in "$@" ; do
	if [ -L "${file_}" ]; then
		if readlink -q "${file_}" >/dev/null ; then
			echo "Good link: ${file_}"
		else
			echo "${file_}: bad link" >/dev/stderr
		fi
	else
		echo "${file_} is not a symlink"
	fi
done

----

=== `buildapp-cmpitg` - builds Common Lisp standalone executable

With https://github.com/xach[@xach's]
http://www.xach.com/lisp/buildapp/[Buildapp].  This script takes
https://common-lisp.net/project/asdf/[ASDF] manifest file from `manifest`
environment variable.  By default, `manifest` is set to
`/m/config/common-lisp/sbcl-quicklisp-manifest.txt`.

.file::buildapp-cmpitg
[source,sh]
----
#!/usr/bin/env rc

if (~ $manifest '') {
	manifest='/m/config/common-lisp/sbcl-quicklisp-manifest.txt'
}

buildapp --manifest-file $manifest \
	--load /m/Toolbox/SBCL/sbcl-cmpitg-base.lisp \
	$*

----

=== `chmod-default [dir]` - fixes permissions

`chmod` a directory recursively, 755 for files and 644 for directories.  By
default, `dir` is current working directory.

.file::chmod-default
[source,sh]
----
#!/bin/bash

test -z "$1" && dir_="." || dir_="$1"

find "${dir_}" -type d -print0 | xargs -0 chmod 0755
find "${dir_}" -type f -print0 | xargs -0 chmod 0644

----

=== `cl-write-manifest` - writes ASDF manifest file

Writes
https://common-lisp.net/project/asia/asia.html#_how_to_create_project_manifest_database[ASDF
manifest] file to a location, set by environment variable `manifest`.  By
default, `manifest` is set to
`/m/config/common-lisp/sbcl-quicklisp-manifest.txt`.

.file::cl-write-manifest
[source,sh]
----
#!/usr/bin/env rc

if (~ $manifest '') {
	manifest='/m/config/common-lisp/sbcl-quicklisp-manifest.txt'
}

echo Writing manifest file $manifest

sbcl-cmpitg --no-userinit --no-sysinit --non-interactive \
	--eval '(ql:write-asdf-manifest-file "'^$manifest^'")'

----

=== `clojure-repl` - starts Clojure REPL with http://leiningen.org/[Lein]

Starts a Clojure REPL in a directory, set by the `clojure_root` environment
variable.  By default, `clojure_root` is set to `${HOME}/test/clojure/main`.

.file::clojure-repl
[source,sh]
----
#!/usr/bin/env rc

if (~ $clojure_root '') {
	clojure_root=$home/test/clojure/main
}

pushd .
cd $clojure_root
lein repl $@
popd

----

=== `comment-code` - comments code, read from stdin

Comments code by prefixing them with line comment character string by the
first argument passed in this script.  By default, prefix code with `# `.

.file::comment-code
[source,sh]
----
#!/usr/bin/env rc

#
# Comments a piece of code.
#

if (~ $1 '') {
	comment_char='#'
}
if not {
	comment_char=$1
}

prefix $comment_char^' '

----

=== `config-keymap-altgr` - keyboard layout: Programmer Dvorak + Right Alt as AltGr + Ctrl-Alt swapped + CapsLock-Escape swapped

.file::config-keymap-altgr
[source,sh]
----
#!/bin/bash

test -z "${DISPLAY}" && exit 0

setxkbmap us -variant dvp -option lv3:ralt_alt
xmodmap <( cat <<EOF
! -*- mode: xmodmap-generic -*-
! No modifier map for mod5
clear mod5
add mod4 = Super_R

! Swap Escape and Capslock
remove Lock = Caps_Lock
add Lock = Escape
keysym Caps_Lock = Escape
keysym Escape = Caps_Lock

! Swap left Control and Alt
remove control = Control_L
remove mod1 = Alt_L
remove mod1 = Meta_L
keysym Control_L = Meta_L
keysym Control_L = Alt_L
keysym Alt_L = Control_L
add mod1 = Meta_L
add mod1 = Alt_L
add control = Control_L

! Swap right Control and Alt
remove control = Control_R
remove mod1 = Alt_R
keysym Control_R = Alt_R
keysym Alt_R = Control_R

add control = Control_R

! Add AltGr to Alt_R
add mod5 = Alt_R

EOF
)

----

=== `config-keymap-cmpitg` - keyboard layout: Programmer Dvorak + Ctrl-Alt swapped + CapsLock-Escape swapped

.file::config-keymap-cmpitg
[source,sh]
----
#!/bin/bash

test -z "${DISPLAY}" && exit 0

##############################################################################

do-notify-short "Setting specialized keylayout"
newline
setxkbmap us -variant dvp -option lv3:ralt_alt
if (test -e ~/.Xmodmap); then
	xmodmap ~/.Xmodmap
else
	xmodmap <( cat <<EOF
! -*- mode: xmodmap-generic -*-
! No modifier map for mod5
clear mod5
add mod4 = Super_R

! Swap Escape and Capslock
remove Lock = Caps_Lock
add Lock = Escape
keysym Caps_Lock = Escape
keysym Escape = Caps_Lock

! Swap left Control and Alt
remove control = Control_L
remove mod1 = Alt_L
remove mod1 = Meta_L
keysym Control_L = Meta_L
keysym Control_L = Alt_L
keysym Alt_L = Control_L
add mod1 = Meta_L
add mod1 = Alt_L
add control = Control_L

! Swap right Control and Alt
remove control = Control_R
remove mod1 = Alt_R
keysym Control_R = Alt_R
keysym Alt_R = Control_R
add mod1 = Alt_R
add control = Control_R

EOF
)
fi

config-logitech-trackball-marble-righty
# config-logitech-trackball-marble-lefty
config-logitech-g300-mouse
config-logitech-g502-mouse
config-lenovo-mouse

config-touchpad
config-touchpad

----

=== `config-keymap-steam` - keyboard layout: Programmer Dvorak without AltGr

Because Steam doesn't work with swapped modifiers.

.file::config-keymap-steam
[source,sh]
----
#!/bin/bash

test -z "${DISPLAY}" && exit 0

do-notify-short "Setting keyboard layout for Steam"
newline
setxkbmap us -variant dvp -option lv3:ralt_alt

config-logitech-g502-mouse

----

=== Config mouses

Enables natural scrolling and tweaks acceleration profile.

==== `config-lenovo-n700-mouse`

.file::config-lenovo-n700-mouse
[source,sh]
----
#!/bin/bash

id_=$(xinput list 2>/dev/null \
			| grep "Dual Mode WL Touch Mouse N700" \
			| head -1 \
			| cut -d'=' -f2 \
			| awk '{ print $1 }')

test -z "${id_}" && exit 0

##############################################################################

do-notify-short "Configuring Dual Mode WL Touch Mouse N700"

do-notify-short "* Set natural scrolling"
xinput set-prop "${id_}" "Evdev Scrolling Distance" -1, -1, 1

do-notify-short "* Set pointer acceleration"
xinput set-prop "${id_}" "Device Accel Profile" 7

----

==== `config-logitech-g300-mouse`

Also, resets keyboard layout for G300 back to US QWERTY, so that
kbd:[Ctrl+X/C/V] works as expected.

.file::config-logitech-g300-mouse
[source,sh]
----
#!/bin/bash

id_=$(xinput list \
			| grep "Logitech Gaming Mouse G300" \
			| head -1 \
			| cut -d'=' -f2 \
			| awk '{ print $1 }')
id_keyboard_=$(xinput list \
					 | grep "Logitech Gaming Mouse G300" \
					 | tail -1 \
					 | cut -d'=' -f2 \
					 | awk '{ print $1 }')

test -z "${id_}"          && exit 0
test -z "${id_keyboard_}" && exit 0

##############################################################################

do-notify-short "Configuring Logitech G300 mouse"

do-notify-short "* Set natural scrolling"
xinput set-prop "${id_}" "Evdev Scrolling Distance" -1, -1, 1

do-notify-short "* Reset keyboard layout"
setxkbmap us -device "${id_keyboard_}"

----

==== `config-logitech-g502-mouse`

.file::config-logitech-g502-mouse
[source,sh]
----
#!/bin/bash

# http://www.x.org/wiki/Development/Documentation/PointerAcceleration/

##############################################################################

id_=$(xinput list \
			 | grep "Logitech Gaming Mouse G502" \
			 | head -1 \
			 | cut -d'=' -f2 \
			 | awk '{ print $1 }')
id_2_=$(xinput list \
			   | grep "Logitech Gaming Mouse G502" \
			   | tail -1 \
			   | cut -d'=' -f2 \
			   | awk '{ print $1 }')

test -z "${id_}"   && exit 0
test -z "${id_2_}" && exit 0

##############################################################################

do-notify "Configuring Logitech G502 mouse
* Set natural scrolling
* Tuning mouse movement
"

for mouse_ in "${id_}" "${id_2_}"; do
	xinput set-prop "${mouse_}" "Evdev Scrolling Distance" -1, -1, 1
	xinput set-prop "${mouse_}" "Device Accel Profile" 7
	xinput set-prop "${mouse_}" "Device Accel Constant Deceleration" 2
	xinput set-prop "${mouse_}" "Device Accel Adaptive Deceleration" 1
done

----

==== `config-logitech-trackball-marble-lefty`

.file::config-logitech-trackball-marble-lefty
[source,sh]
----
#!/bin/bash

# Sources:
#   https://wiki.archlinux.org/index.php/Logitech_Marble_Mouse
#   http://www.x.org/wiki/Development/Documentation/PointerAcceleration/
#   http://www.x.org/archive/X11R7.5/doc/man/man4/evdev.4.html
#   man evdev

id_=$( \
	xinput list \
	| grep "Logitech USB Trackball" \
	| head -1 \
	| cut -d'=' -f2 \
	| awk '{ print $1 }' \
)

test -z "${id_}" && exit 0

# ID     	Hardware Action     	Result                
# 1 	Large button left 	normal click
# 2 	Both large buttons 	middle-click  †
# 3 	Large button right 	right-click
# 4 	(not a button) 	-
# 5 	(not a button) 	-
# 6 	(not a button) 	-
# 7 	(not a button) 	-
# 8 	Small button left 	browser back
# 9 	Small button right 	browser forward


# * big-left: Primary click
# * big-right: Secondary click
# * small-left: Scrolling
# * small-right: Middle click
do-notify-short """Config buttons for righties:
   large-left  [1]: Left click
   large-right [3]: Right click
   small-left  [8]: Middle click
   small-right [9]: Scrolling + Middle click"""
newline
# xinput set-button-map "${id_}" 1 9 3 4 5 6 7 2 9
xinput set-button-map "${id_}" 3 9 1 4 5 6 7 2 2

# small-left
# xinput set-prop "${id_}" "Evdev Wheel Emulation Button" 8
xinput set-prop "${id_}" "Evdev Wheel Emulation Button" 9

# Enable wheel emulation
xinput set-prop "${id_}" "Evdev Wheel Emulation"        1

##############################################################################

do-notify-short "Config inverted and horizontial scrolling"

# For normal scrolling
# xinput set-prop "${id_}" "Evdev Wheel Emulation Axes" 6 7 4 5

# Inverted scrolling
xinput set-prop "${id_}" "Evdev Wheel Emulation Axes" 7 6 5 4

# Inverted direction
xinput set-prop "${id_}" "Evdev Axis Inversion" 1 1

##############################################################################

do-notify-short "Config profile: Fast movement but more control at pixel-level"
newline

# Default
# Debian
# xinput set-prop "${id_}" "Device Accel Constant Deceleration" 1.5
xinput set-prop "${id_}" "Device Accel Constant Deceleration" 1.5

# More precision
# xinput set-prop "${id_}" "Device Accel Adaptive Deceleration" 5
xinput set-prop "${id_}" "Device Accel Adaptive Deceleration" 1

# Acceleration
#   http://www.x.org/wiki/Development/Documentation/PointerAcceleration/
# xinput set-prop "${id_}" "Device Accel Profile" -1
# xinput set-prop "${id_}" "Device Accel Profile" 6
xinput set-prop "${id_}" "Device Accel Profile" 2
# Debian
xinput set-prop "${id_}" "Device Accel Velocity Scaling" 5
# xinput set-prop "${id_}" "Device Accel Velocity Scaling" 1
# xinput set-prop "${id_}" "Device Accel Velocity Scaling" 1

----

==== `config-logitech-trackball-marble-lefty`

.file::config-logitech-trackball-marble-lefty
[source,sh]
----
#!/bin/bash

# Sources:
#   https://wiki.archlinux.org/index.php/Logitech_Marble_Mouse
#   http://www.x.org/wiki/Development/Documentation/PointerAcceleration/
#   http://www.x.org/archive/X11R7.5/doc/man/man4/evdev.4.html
#   man evdev

id_=$( \
	xinput list \
	| grep "Logitech USB Trackball" \
	| head -1 \
	| cut -d'=' -f2 \
	| awk '{ print $1 }' \
)

test -z "${id_}" && exit 0

# ID     	Hardware Action     	Result                
# 1 	Large button left 	normal click
# 2 	Both large buttons 	middle-click  †
# 3 	Large button right 	right-click
# 4 	(not a button) 	-
# 5 	(not a button) 	-
# 6 	(not a button) 	-
# 7 	(not a button) 	-
# 8 	Small button left 	browser back
# 9 	Small button right 	browser forward


# * big-left: Primary click
# * big-right: Secondary click
# * small-left: Scrolling
# * small-right: Middle click
do-notify-short """Config buttons for righties:
   large-left  [1]: Left click
   large-right [3]: Right click
   small-left  [8]: Middle click
   small-right [9]: Scrolling + Middle click"""
newline
xinput set-button-map "${id_}" 1 9 3 4 5 6 7 2 9
# xinput set-button-map "${id_}" 3 9 1 4 5 6 7 2 2

# small-left
xinput set-prop "${id_}" "Evdev Wheel Emulation Button" 8
# xinput set-prop "${id_}" "Evdev Wheel Emulation Button" 9

# Enable wheel emulation
xinput set-prop "${id_}" "Evdev Wheel Emulation"        1

##############################################################################

do-notify-short "Config inverted and horizontial scrolling"
newline

# For normal scrolling
# xinput set-prop "${id_}" "Evdev Wheel Emulation Axes" 6 7 4 5

# Inverted scrolling
xinput set-prop "${id_}" "Evdev Wheel Emulation Axes" 7 6 5 4

# Inverted direction
xinput set-prop "${id_}" "Evdev Axis Inversion" 1 1
# xinput set-prop "${id_}" "Evdev Axis Inversion" 0 1

##############################################################################

do-notify-short "Config profile: Fast movement but more control at pixel-level"
newline

# Default
# Debian
# xinput set-prop "${id_}" "Device Accel Constant Deceleration" 1.5
xinput set-prop "${id_}" "Device Accel Constant Deceleration" 1.5

# More precision
# xinput set-prop "${id_}" "Device Accel Adaptive Deceleration" 5
xinput set-prop "${id_}" "Device Accel Adaptive Deceleration" 1

# Acceleration
# xinput set-prop "${id_}" "Device Accel Profile" -1
xinput set-prop "${id_}" "Device Accel Profile" 6
# Debian
# xinput set-prop "${id_}" "Device Accel Velocity Scaling" 5
xinput set-prop "${id_}" "Device Accel Velocity Scaling" 1

----

==== `config-touchpad`

Lots of tweaks, the code should be self-explanatory though.

.file::config-touchpad
[source,sh]
----
#!/bin/bash

(xinput list | grep -i touchpad &>/dev/null) || exit 0

##############################################################################

do-notify-short """Configuring touchpad
* Setting natural scrolling
* Enabling tapping
* Enabling two-finger tapping as secondary click"""
newline

# Edge
# synclient LeftEdge=1200
# synclient RightEdge=5100
# synclient TopEdge=1000
# synclient BottomEdge=4600

# synclient LeftEdge=1000
# synclient RightEdge=5200
# synclient TopEdge=1000
# synclient BottomEdge=5000

# Palm detection
synclient PalmDetect=1

# Tap
synclient MaxTapTime=180
synclient MaxTapMove=221
synclient MaxDoubleTapTime=100
synclient SingleTapTimeout=180
synclient EmulateTwoFingerMinZ=1
synclient EmulateTwoFingerMinW=7
synclient VertEdgeScroll=1
synclient HorizEdgeScroll=1

# Corner
synclient RTCornerButton=0
synclient RBCornerButton=0
synclient LTCornerButton=1
synclient LBCornerButton=0
# synclient TapButton1=3
# synclient TapButton2=1
# synclient TapButton3=2
# synclient TapButton1=1
# synclient TapButton2=2
# synclient TapButton3=3
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient ClickFinger1=1
synclient ClickFinger2=1
synclient ClickFinger3=2
synclient CircularScrolling=0

# Natural scrolling
synclient VertScrollDelta=-111
synclient HorizScrollDelta=-111
synclient VertEdgeScroll=0
synclient HorizEdgeScroll=0

# xinput get-button-map "SynPS/2 Synaptics TouchPad" 1 2 3 4 5 6 7 8 9 10 11 12

----


=== `config-monitors-urt` - configs external monitor for http://www.urbanterror.info[Urban Terror]

Disables laptop monitor and increases brightness, as the brightness option
doesn't work in-game.

.file::config-monitors-urt
[source,sh]
----
#!/usr/bin/env rc

laptop_mon=eDP1
main_mon=HDMI1
gamma=1.4

xrandr --output $laptop_mon --off
sleep 2
xrandr --output $main_mon --mode 1280x1024
xrandr --output $main_mon --gamma $gamma:$gamma:$gamma

----

=== `convert-to-mp3` - converts files to MP3

This script takes a list of files as arguments.

TODO: this should be in Rc, not Zsh.

.file::convert-to-mp3
[source,sh]
----
#!/bin/zsh

which ffpmeg &>/dev/null && prog_=ffmpeg || prog_=avconv

for f in $*; do
	"${prog_}" -i "${f}" -vn -aq 1 "$f:r.mp3"
done

----

=== `convert-to-ogg-vorbis` - converts files to Ogg Vorbis

This script takes a list of files as arguments.

TODO: this should be in Rc, not Zsh.

.file::convert-to-ogg-vorbis
[source,sh]
----
#!/bin/zsh

which ffpmeg &>/dev/null && prog_=ffmpeg || prog_=avconv

for f in $*; do
	"${prog_}" -i "${f}" -vn -aq 1 "$f:r.ogg"
done

----

=== `count-monitors`

.file::count-monitors
[source,sh]
----
#!/bin/bash

xrandr | grep " connected" | wc -l

----

=== `cpu-usage`

Returns the average CPU usage measured in 3 consecutive seconds, using `mpstat`.

.file::cpu-usage
[source,sh]
----
#!/bin/bash

#
# Using `mpstat', calculates average CPU usage in 3 seconds.
#

if ! which mpstat &>/dev/null ; then
	echo You need mpstat installed for this command to work >&2
	exit 1
fi

mpstat 3 1 | tail -1 | gawk '$12 ~ /[0-9.]+/ { print 100 - $12"%" }'

----

=== `create-ctags`

.file::create-ctags
[source,sh]
----
#!/bin/bash

#
# Creates a tags file named TAGS using ctags.
#

if ! which ctags &>/dev/null ; then
	echo You need ctags installed for this command to work >&2
	exit 1
fi

if test -z "$1"; then
	cat <<EOF
Usage: $0 <directory> [ctags-options]*

Creates a tags file named TAGS using ctags.
EOF
	exit 2
fi

dir_name_="$1"
shift

ctags "$@" -f "${dir_name_}"/TAGS -R "${dir_name_}"/*

----

=== `create-sbcl-cmpitg-image` - dumping a customized SBCL image

Dumps a customized SBCL image and makes it work with Shelly (if installed).

.file::create-sbcl-cmpitg-image
[source,sh]
----
#!/usr/bin/env rc

if (~ $1 -h --help) {
	cat <<EOF
	exit 1
}
Dumps an SBCL image and makes it work with Shelly (if installed).

Usage: $0 [--core-path core-file] [--eval sexp]

Options:

--core-path :: Path to SBCL core file to dump to, default value:
               '/m/opt/sbcl-images/sbcl-$USER.core'.
--eval      :: The Sexp to evaluate before dumping, default value:
               '(load "/m/Toolbox/SBCL/sbcl-$USER-base.lisp")'.
EOF

##############################################################################
# Sanity check
##############################################################################

if (! which sbcl >/dev/null >[2=1]) {
	echo sbcl executable not found.  Do you have SBCL installed? >[1=2]
	exit 1
}
if not {
	sbcl_version=`{sbcl --version | cut -d' ' -f2}
}

##############################################################################

fn try_set_vars {
	switch ($1) {
	case --core-path
		core_path=$2
	case --eval
		sexp=$2
	}

	if (~ $core_path '') {
		core_path=/m/opt/sbcl-images/sbcl-$USER.core
	}
	if (~ $sexp '') {
		sexp='(load "/m/Toolbox/SBCL/sbcl-'$USER'-base.lisp")'
	}
}

try_set_vars $1 $2
try_set_vars $3 $4

if (! ~ $SHELLY_HOME '') {
	shelly_core_path=$SHELLY_HOME^'/dumped-cores/sbcl-'^$sbcl_version^'.core'
}

##############################################################################

echo Core path: $core_path
echo Sexp: $sexp
if (! ~ $shelly_core_path '') {
	echo Shelly found, path to core: $shelly_core_path
}

echo '-> Dumping core'
sbcl --noinform \
	--no-userinit \
	--eval $sexp \
	--eval '(sb-ext:save-lisp-and-die "'^$core_path^'")'
 
if (test -d $SHELLY_HOME/dumped-cores) {
	echo '-> Updating Shelly'
	cp -fv $core_path $shelly_core_path
	cp -fv $core_path $SHELLY_HOME/dumped-cores/sbcl.core
}

----

=== `json-post` - makes a JSON POST

.file::json-post
[source,sh]
----
#!/usr/bin/env rc

#
# Makes a JSON POST with Curl
#

if (! which curl >/dev/null >[2=1]) {
	echo You need to install Curl >[1=2]
	exit 1
}

curl -i -H 'Content-Type: application/json' -X POST $*

----

=== `do-notify` - sends a desktop notification

.file::do-notify
[source,sh]
----
#!/usr/bin/env rc

echo $*

if (which notify-send >/dev/null >[2=1]) {
	notify-send $*
}

----

=== `do-notify-short` - sends a short desktop notification

.file::do-notify-short
[source,sh]
----
#!/usr/bin/env rc

echo $*

if (which notify-send >/dev/null >[2=1]) {
	notify-send -t 2000 $*
}

----

=== `docker-remove-orphaned-containers`

.file::docker-remove-orphaned-containers
[source,sh]
----
#!/bin/bash

docker rm $(docker ps -aq)

----

=== `docker-remove-unnamed-images`

.file::docker-remove-unnamed-images
[source,sh]
----
#!/bin/bash

docker images -a | grep "<none>" | awk '{ print $3 }' | xargs docker rmi

----

=== `drop-lines`

.file::drop-lines
[source,sh]
----
#!/usr/bin/env rc

#
# Drops the first $1 lines.
#

n_lines=$1
n_lines=`{echo $n_lines + 1 | bc}
tail -n +$n_lines

----

=== `en2fi` - translates from English to Finnish

.file::en2fi
[source,sh]
----
#!/usr/bin/env rc

#
# Translates from English to Finnish with Google Translate, using
# soimort/translate-shell tool.
#

if (! which trans >/dev/null >[2=1]) {
	echo trans command not found >[1=2]
	echo Make sure you have soimort/translate-shell installed >[1=2]
	exit 1
}

TARGET_LANG=fi gtranslate $*

----

=== `fi2en` - translates from Finnish to English

.file::fi2en
[source,sh]
----
#!/usr/bin/env rc

#
# Translates from Finnish to English with Google Translate, using
# soimort/translate-shell tool.
#

if (! which trans >/dev/null >[2=1]) {
	echo trans command not found >[1=2]
	echo Make sure you have soimort/translate-shell installed >[1=2]
	exit 1
}

TARGET_LANG=en gtranslate $*

----

anchor:ff[]

=== `ff` - quickly opens file with Emacs and https://github.com/cmpitg/emnode[Emnode]

Quickly opens file with Emacs + https://github.com/cmpitg/emnode[Emnode]
server.  Emacs has to be setup with Emnode to listen to port `EMACS_PORT`,
handling `/open/<file-path>` URI (i.e. command `curl 0:${EMACS_PORT}/open//m/src` opens
`/m/src` in Emacs).  Sample setup is as followed:

[source,lisp]
----
(setq *emnode-routes*
      '(("^.*//open/\\(.*\\)"  . ~ipc-open-file)))

(defun ~ipc-open-file (httpcon)
  (let ((path (emnode:http-get-arg httpcon 1)))
    (emnode:http-start httpcon 200 '("Content-Type" . "text/plain"))
    (emnode:http-end httpcon (format "> Opening: %s\n" path))
    (find-file path)))

;; $ curl 0:9999/open//m/src

(use-package emnode
  :path "/m/src/emnode"
  :ensure elnode
  :config
  (progn
    (setq emnode:*log-level* emnode:+log-none+)
    (emnode:stop 9999)
    (ignore-errors
      (emnode:start-server *emnode-routes* :port 9999))))

----

If Emacs is not yet started or not listening on port `EMACS_PORT`, start one
with custom Emacs init file stored in environment variable `EMACS_INIT`.  By
default, `EMACS_INIT` is set to `"~/emacs-config/src/init.el"` and
`EMACS_PORT` is set to `9999`.

TODO: Handling file pattern: `<path>:line`, `<path>:line-1:line-2`,
`<path>:/regex/`

.file::ff
[source,sh]
----
#!/bin/bash

if [[ -z "$EMACS_INIT" ]]; then
	EMACS_INIT="~/emacs-config/src/init.el"
fi

if [[ -z "$EMACS_PORT" ]]; then
	EMACS_PORT=9999
fi

(curl 0:$EMACS_PORT &>/dev/null) && server_running_p_=1 || server_running_p_=0

if [[ "${server_running_p_}" -eq "1" ]] ; then
	if [[ "$1" == /* ]] ; then
		curl "0:${EMACS_PORT}/open/$1"
	else
		curl "0:${EMACS_PORT}/open/$PWD/$1"
	fi
else
	emacs -Q -l "${EMACS_INIT}" "$@"
fi

----

=== `ffb` - quickly open `/m/bin/<file>` with <<ff,`ff`>>

.file::ffb
[source,sh]
----
#!/bin/bash

ff "/m/bin/$@"

----

=== `format-text` - formats text from stdin using Emacs's `fill-paragraph`

.file::format-text
[source,sh]
----
#!/usr/bin/env rc

#
# Formats text from stdin using Emacs's fill-paragraph.
#

input=`{cat}
sexpr=`{echo `{cat <<EOF}}

(with-temp-buffer
  (set-fill-column 78)
  (insert "$input")
  (end-of-buffer)
  (fill-region 0 (point))
  (princ (buffer-string)))
EOF

emacs --batch --eval $"sexpr $* >[2]/dev/null

----

=== `monitors-info` - retrieves information of connected monitors

.file::monitors-info
[source,sh]
----
#!/usr/bin/env rc

#
# Retrieves information of the currently connected monitors and outputs as
# followed:
# * First name: <number of monitors>
# * Second line: <monitor> <mode> <rate>
#

lines=`{xrandr \
	| grep ' connected' \
	| cut -d' ' -f1}

echo $#lines
for (output in $lines) {
	data=`{xrandr \
		| take-from $output \
		| drop-lines 1 \
		| take-lines 1 \
		| tr -d '*' \
		| tr -d '+'}
	mode=`{echo $data | cut -d' ' -f1}
	rate=`{echo $data | cut -d' ' -f2}
	echo $output $mode $rate
}

----

=== `git-rm-orphaned` - removes orphaned files from Git

.file::git-rm-orphaned
[source,sh]
----
#!/bin/bash

git ls-files --deleted | xargs git rm --cached

----

=== `nix` - runs a command with Nix (if exists)

.file::nix
[source,sh]
----
#!/bin/bash

export NIX_PATH=$(ls -d -1 /m/opt/nix-1.10 | head -1)

. ${NIX_PATH}/scripts/nix-profile.sh
exec "$@"

----

=== `uri-github2ssh` - converts Github URI to `git+ssh` style

.file::uri-github2ssh
[source,sh]
----
#!/usr/bin/env rc

#
# git@github.com:schacon/hg-git.git
# git+ssh://git@github.com/schacon/hg-git.git
#

program=`{basename $0}

if (~ $1 '' '--help') {
	cat <<USAGE
	exit 1
}
Usage: $program git@github.com:<user>/<repo>

Converts to universal git+ssh style repository URI.

E.g.

  $program git@github.com:schacon/hg-git.git
  # ⇨ git+ssh://git@github.com/schacon/hg-git.git
USAGE

uri=`{echo $1 | sed 's/:/\//g' | sed 's/git\/\/\///g'}

echo 'git+ssh://'$uri

----

=== `gitserve` - runs a Git server

.file::gitserve
[source,sh]
----
#!/usr/bin/env rc

#
# Runs a Git server.
#

program=`{basename $0}

if (~ $1 '-h' '--help') {
	cat <<USAGE
	exit 0
}
Usage:

Runs a Git server.

  $program             :: Take current directory as Git repository
  $program <git-repo>  :: Take a specific Git repository

By default, the Git server is opened on port 4242.  This could be overriden by
setting the environment variable GIT_PORT.  For example: run a Git server on 
port 5454, serving content from Git repo at /m/bin:

  GIT_PORT=5454 $program /m/bin

Then, you can clone the repo with: git clone git://<host>:<port>/ <repo-name>

Note that this method is a quick way to share Git repository and it's not at
all secure.  In practice, you might want to Git server behind a reverse proxy.
USAGE

(test $#GIT_PORT -eq 0) && git_port=4242 || git_port=$GIT_PORT
(test $#1        -eq 0) && git_path='.'  || git_path=$1

exec git daemon --reuseaddr '--base-path='$git_path --export-all --verbose '--port='$git_port

----

=== `gtranslate` - translates from stdin with Google Translate

.file::gtranslate
[source,sh]
----
#!/usr/bin/env rc

#
# Translates with Google Translate, using soimort/translate-shell tool.
#

if (! which trans >/dev/null >[2=1]) {
	echo trans command not found >[1=2]
	echo Make sure you have soimort/translate-shell installed >[1=2]
	exit 1
}

input=`{cat}
trans $* -brief $"input

----

=== `html2text`

.file::html2text
[source,sh]
----
#!/bin/bash

#
# Converts HTML to text.  HTML is read from stdin.
#

if ! which lynx &>/dev/null; then
	echo lynx not found. >&2
	echo Make sure you have Lynx installed. >&2
	exit 1
fi

exec lynx -dump -stdin "$@"

----

=== `i3-exec-command` - executes an http://i3wm.org/[i3] command

.file::i3-exec-command
[source,sh]
----
#!/bin/bash

i3-input -f 'pango:Droid Sans 10' "$@"

----

=== `i3-move-to-workspace` - moves a window to a workspace with http://i3wm.org/[i3]

.file::i3-move-to-workspace
[source,sh]
----
#!/bin/bash

i3-input \
	-f 'pango:Droid Sans 10' \
	-F 'move workspace "%s"' \
	-P 'Move window to workspace: ' %s

----

=== `i3-rename-workspace` - renames current workspace in http://i3wm.org/[i3]

.file::i3-rename-workspace
[source,sh]
----
#!/bin/bash

i3-input \
	-f 'pango:Droid Sans 10' \
	-F 'rename workspace to "%s"' \
	-P 'Rename workspace: ' %s

----

=== `i3-switch-window` - window switcher for http://i3wm.org/[i3]

Requirement: `dmenu`.

.file::i3-switch-window
[source,python]
----
#!/usr/bin/env python3

#
# This file is part of i3-switch-window project.
#
# Copyright (C) 2015  Ha-Duong Nguyen <cmpitg@gmail.com>
#
# i3-switch-window is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# i3-switch-window is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# i3-switch-window.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Requirements:
#   Python 3
#   dmenu with Xft patch
#

import json
import subprocess


# dmenu_options      = '-b -i -l 40 -fn "Droid Sans-10" -nf "#ffa077" -nb "#202020"'
dmenu_options      = '-p Window -i -l 40 -fn "Droid Sans-10" -nf "#ffa077" -nb "#202020"'
title_format       = "{} — {}"
cmd_get_tree       = "i3-msg -t get_tree"
cmd_switch_window  = "i3-msg '[con_id={}] focus'"


# TODO: Check if dmenu is available


def main():
    global dmenu_options
    global cmd_get_tree
    global cmd_switch_window

    tree = json.loads(subprocess.check_output(
        cmd_get_tree,
        stderr=subprocess.STDOUT,
        shell=True
    ).decode('utf-8'))

    windows       = get_all_windows(tree)
    lookup_table  = build_lookup_table(windows)
    chosen        = dmenu(itemize(windows), dmenu_options)

    switch_to_window(
        chosen=chosen,
        table=lookup_table,
        cmd=cmd_switch_window
    )


def switch_to_window(chosen, table, cmd):
    window_id = table.get(chosen, "")
    subprocess.check_call(cmd.format(window_id), shell=True)


def window_as_string(with_id=False):
    global title_format

    def helper(window):
        title = title_format.format(window['class'], window['title'])
        if with_id:
            return title, window['id']
        else:
            return title

    return helper


def build_lookup_table(windows):
    stringifized = map(window_as_string(with_id=True), windows)
    return dict(stringifized)


def itemize(windows):
    """
    Itemize windows list for dmenu.
    """
    return "\n".join(map(window_as_string(with_id=False), windows))


def get_all_windows(tree):
    """
    Extracts all windows from i3 tree.
    """
    # Add current window
    if is_window(tree):
        result = [standardize_window(tree)]
    else:
        result = []

    # Add child windows
    children = []
    for window in tree['nodes']:
        children += get_all_windows(window)

    return result + children


def is_window(tree):
    """
    Determines if a tree is a window.
    """
    return tree['window'] \
        and tree['window_properties']['class'].lower().find('panel') == -1


def standardize_window(window):
    """
    Extracts necessary information for a window.
    """
    return {
        'id':       window['id'],
        'title':    window['window_properties']['title'],
        'class':    window['window_properties']['class'],
        'instance': window['window_properties']['instance']
    }


def dmenu(items, dmenu_options):
    """
    Calls dmenu to display and menu for window switching.
    """
    cmd = subprocess.Popen(
        "dmenu {}".format(dmenu_options),
        shell=True,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, _ = cmd.communicate(items.encode('utf-8'))
    return stdout.decode('utf-8').strip('\n')


if __name__ == '__main__':
    main()

----

=== `i3-switch-workspace` - workspace switcher for http://i3wm.org/[i3]

Requirement: `dmenu`.

.file::i3-switch-workspace
[source,python]
----
#!/usr/bin/env python3

#
# This file is part of i3-switch-window project.
#
# Copyright (C) 2015  Ha-Duong Nguyen <cmpitg@gmail.com>
#
# i3-switch-window is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# i3-switch-window is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# i3-switch-window.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Requirements:
#   Python 3
#   dmenu with Xft patch
#

import json
import subprocess


dmenu_options         = '-p Workspace -i -l 30 -fn "Droid Sans-10" -nf "#ffa077" -nb "#202020"'
# dmenu_options         = '-p Workspace -b -i -l 30 -fn "Droid Sans-10" -nf "#ffa077" -nb "#202020"'
cmd_get_workspaces    = "i3-msg -t get_workspaces"
cmd_switch_workspace  = "i3-msg 'workspace {}'"


# TODO: Check if dmenu exists


def main():
    global dmenu_options
    global cmd_get_workspaces
    global cmd_switch_workspace

    workspaces = filter_workspaces(json.loads(subprocess.check_output(
        cmd_get_workspaces,
        stderr=subprocess.STDOUT,
        shell=True
    ).decode('utf-8')))

    chosen = dmenu(itemize(workspaces), dmenu_options)

    switch_to_workspace(
        chosen=chosen,
        cmd=cmd_switch_workspace
    )


def switch_to_workspace(chosen, cmd):
    """
    Switch to a chosen workspace.
    """
    subprocess.check_call(cmd.format(chosen), shell=True)


def filter_workspaces(workspaces):
    """
    Filter out current workspace.
    """
    return [
        w
        for w in workspaces
        if not w.get('focused', False)
    ]


def itemize(workspaces):
    """
    Itemize workspaces list for dmenu.
    """
    return "\n".join(map(lambda w: w['name'], workspaces))


def dmenu(items, dmenu_options):
    cmd = subprocess.Popen(
        "dmenu {}".format(dmenu_options),
        shell=True,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, _ = cmd.communicate(items.encode('utf-8'))
    return stdout.decode('utf-8').strip('\n')


if __name__ == '__main__':
    main()

----

=== `i3-to-workspace` - jumps to a workspace by name in http://i3wm.org/[i3]

.file::i3-to-workspace
[source,sh]
----
#!/bin/bash

i3-input -f 'pango:Droid Sans 10' -F 'workspace "%s"' -P 'Go to workspace: ' %s

----

=== `join-lines`

Joins all lines using Plan 9's tr.

.file::join-lines
[source,sh]
----
#!/usr/bin/env rc

#
# Joins all lines into one using Plan 9's tr.
#

tr '
' ' '
----

=== `all-dev-debs` - lists all Debian `-dev` packages installed

.file::all-dev-debs
[source,sh]
----
#!/bin/bash

dpkg-query -l '*dev' | grep "^.i" | awk '{ print $2 }' | grep "\-dev$"

----

=== `local-tcp-open-p` - checks if a local TCP port is opened

.file::local-tcp-open-p
[source,sh]
----
#!/bin/bash

if (test $# -eq 0); then
	cat <<EOF
Usage: `basename $0` <port>

Determines if a local TCP port is open.  Returns 0 if it is or 1 otherwise.
EOF
fi

if ! which nc &>/dev/null; then
	echo nc not found. >&2
	echo Make sure you have Netcat installed. >&2
	exit 2
fi

nc -z 127.0.0.1 "$1"

----

=== `lockscreen`

.file::lockscreen
[source,sh]
----
#!/bin/bash

# pgrep lightdm && gdmflexiserver || gnome-screensaver-command -l
xscreensaver-command -lock \
	|| gnome-screensaver-command -l \
	|| (sh -c "dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock")

----

=== `monitor-off`

.file::monitor-off
[source,sh]
----
xset -display :0 dpms force off

----

=== `now-standardized`

.file::now-standardized
[source,sh]
----
#!/usr/bin/env rc

#
# This script depends directly on `date' command, taking no addition argument,
# thus original sh is enough.
#

exec /bin/date '+%Y-%m-%d_%H-%M-%S'

----

=== `now-to-clipboard`

.file::now-to-clipboard
[source,sh]
----
#!/bin/bash

xterm -e 'date -R | xsel -b'

----

=== `found-executable-p`

.file::found-executable-p
[source,sh]
----
#!/bin/bash

#
# Determines if a executable is found in $PATH
#

which "$1" &>/dev/null

----

=== `prefix` - prefixes all lines read from stdin with a string

.file::prefix
[source,sh]
----
#!/usr/bin/env rc

#
# Prefixes all lines read from stdin.
#

prefix=$1 {
	if (test $#prefix -eq 0) {
		prefix='# '
	}
	sed 's/^/'^$prefix^'/g'
}

----

=== `pretty-print-json`

.file::pretty-print-json
[source,sh]
----
#!/bin/bash

python -m json.tool "$@"

----

=== `psx` - `ps -ef | grep --color "$@"`

.file::psx
[source,sh]
----
#!/bin/bash

ps -ef | grep --color "$@"

----

=== `py2` - runs Python 2 in a http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtual environment]

The name of the virtual environment could be set by setting the `VIRTUAL_ENV`
environment variable.  By default, it uses `python2-full-debian` as its name.

.file::py2
[source,sh]
----
#!/bin/bash

virtualenv_=${VIRTUAL_ENV:-python2-full-debian}

source "${WORKON_HOME}/${virtualenv_}/bin/activate"
exec python "$@"

----

=== `py3` - runs Python 3 in a http://docs.python-guide.org/en/latest/dev/virtualenvs/[virtual environment]

The name of the virtual environment could be set by setting the `VIRTUAL_ENV`
environment variable.  By default, it uses `python2-full-debian` as its name.

.file::py3
[source,sh]
----
#!/bin/bash

virtualenv_=${VIRTUAL_ENV:-python2-full-debian}

source "${WORKON_HOME}/${virtualenv_}/bin/activate"
exec python3 "$@"

----

=== `site-packages-path` - prints Python site packages path

.file::site-packages-path
[source,sh]
----
#!/usr/bin/env python

from distutils.sysconfig import get_python_lib


print(get_python_lib())

----

=== `rc` - runs RC shell with Plan 9 Port environment

.file::rc
[source,sh]
----
#!/bin/bash

exec 9 rc "$@"

----

=== `system-temperature`

.file::system-temperature
[source,sh]
----
#!/bin/bash

echo "-> Starting HDDTemp if necessary"
nc localhost 7634 &>/dev/null || (
    exec sudo hddtemp -d /dev/sda
)
echo ""

echo "-> HDD temperature"
nc localhost 7634

echo "-> CPU temperature"
sensors

----

=== `running-p` - determines if a process is running

.file::running-p
[source,sh]
----
#!/bin/bash

#
# Determines if a process is running using pgrep.
#

exec pgrep "$@" &>/dev/null

----

=== `show-keyboard` - shows keyboard of modifiers, convenient when making screencast

.file::show-keyboard
[source,sh]
----
#!/bin/bash

if ! found-executable-p key-mon; then
	echo key-mon not found. >&2
	echo Make sure you have key-mon installed. >&2
	exit 1
fi

key-mon --decorated --meta --theme modern "$@"

----

=== `suspend-me` - suspends computer

.file::suspend-me
[source,sh]
----
#!/bin/bash

# exec sudo pm-suspend && lockscreen
exec sudo pm-suspend

----

=== `take-from` - takes all lines from stdin, starting from a pattern

.file::take-from
[source,sh]
----
#!/usr/bin/env rc

#
# Takes all lines from a pattern (representing by $1), using GNU Awk.
#

gawk 'BEGIN {
	found = 0
}
/'^$1^'/ {
	found = 1
}
{
	if (found == 1) {
		print $0
	}
}'

----

=== `take-lines` - takes the first `n` lines

.file::take-lines
[source,sh]
----
#!/usr/bin/env rc

#
# Takes the first $1 lines using Plan 9's seq.
#

if (test $#* -eq 0) {
    n_lines=1
}
if not {
    n_lines=$1
}
sed $n_lines^q

----
=== `wget-site`

.file::wget-site
[source,sh]
----
#!/bin/bash

wget \
    --recursive \
    --no-clobber \
    --page-requisites \
    --html-extension \
    --convert-links \
    --timestamping \
    --no-parent \
    --mirror \
    $*

#
# --recursive             download the entire Web site.
# --domains website.org   don't follow links outside website.org.
# --no-parent             don't follow links outside the directory tutorials/html/.
# --page-requisites       get all the elements that compose the page (images, CSS and so on).
# --html-extension        save files with the .html extension.
# --convert-links         convert links so that they work locally, off-line.
# --no-clobber            don't overwrite any existing files (used in case the download is interrupted and
#                         resumed).
# --mirror                create mirror
#

----

=== `start-xephyr` - starts a Xephyr server (for debugging window manager)

TODO: Help text

.file::start-xephyr
[source,sh]
----
#!/bin/bash

if ! which Xephyr &>/dev/null; then
	echo Xephyr not found. >&2
	echo Make sure you have Xephyr installed. >&2
	exit 1
fi

resolution_=${RESOLUTION:-800x600}

Xephyr \
	-ac \
	-br \
	-noreset \
	-screen ${resolution_} \
	:1 "$@" >/dev/null & disown

# export DISPLAY=:1.0
echo Display: $DISPLAY

----

=== `openfile-dialog` - creates a open-file dialog and prints the selected path to stdout

.file::openfile-dialog
[source,sh]
----
#!/bin/bash

if ! which zenity &>/dev/null; then
	echo zenity not found. >&2
	echo Make sure you have Zenity installed. >&2
	exit 1
fi

zenity --file-selection \
	--filename `pwd` "$@" 2>/dev/null

----

== Legacy/Unused scripts

=== `update-sbcl.ruby`

.file::update-sbcl.ruby
[source,ruby]
----
#!/usr/bin/env ruby

#
# Requirements: Nokogiri, libarchive-ruby
#     # In Debian, with RVM
#     sudo aptitude install libarchive-dev
#     gem install nokogiri libarchive-ruby
#
# Check for the latest version of Steel Bank Common Lisp by:
# * Access a SourceForge's mirror as a HTTP page
# * Find all available version strings on the page
# * Loop through all versions in descending order:
#   - If there is a Linux AMD64 tarball, download to DOWNLOAD_DESTINATION
#   - If there isn't a Linux AMD64 tarball for that version, proceed the
#     next one
# * Checksum
# * Extract to DOWNLOAD_DESTINATION
# * Install using `INSTALL_ROOT=#{INSTALL_DESTINATION} sh ./install.sh`
# * Copy the core to INSTALL_DESTINATION
# * Check to see if the SBCL_HOME env var is already exists and remind of
#   adding
#
# Note: The code is verbose because I want to make full use of Ruby, not
# calling shell command unless I have no choice.
#
# Debate: Forking is expensive, but it doesn't matter in this case.  Should I
# use external tool instead of Ruby?
#

require 'nokogiri'
require 'open-uri'
require 'net/http'
require 'archive'
require 'fileutils'

DOWNLOAD_DESTINATION = "/m/cmpitg/opt/"
INSTALL_DESTINATION  = File.expand_path "~/opt/sbcl/"

SITE_NAME            = "www.mirrorservice.org"
SITE_PATH            = "/sites/ftp.sourceforge.net/pub/sourceforge/s/sb/sbcl/sbcl/"
SBCL_DOWNLOAD_URL    = "http://#{SITE_NAME}/#{SITE_PATH}"
SBCL_TARBALL_FORMAT  = "sbcl-%{version}-x86-64-linux-binary.tar.bz2"

def main
  versions         = get_version_strings
  current_version  = get_current_version
  latest_version   = get_latest_version_string versions

  if latest_version == ""
    puts "There's some problem with the site, please check the URLs in #{__file__}"
    return
  end

  puts "Current version: #{current_version}"
  puts "Latest version: #{latest_version}"

  puts
  if current_version != latest_version
    puts "Start downloading latest version"
    download_latest latest_version
    extract_tarball latest_version
  else
    puts "You already have the latest version! :-)"
  end
end

# Public: Remind user of setting up SBCL_HOME and PATH
def remind_setting_up_env
  puts
  if ENV["SBCL_HOME"] == "" || !system("which sbcl >/dev/null 2>&1")
    puts "Be sure to set something similar to:"
    puts "    SBCL_HOME=#{INSTALL_DESTINATION}"
    puts "    PATH=#{INSTALL_DESTINATION}/bin"
    puts "in your shell's rc file.  You might want to consider aliasing sbcl" \
         "with GNU Readline and adding it to your shell's rc:"
    puts "    alias sbcl='rlwrap sbcl'"
  else
    puts "Found SBCL_HOME and sbcl in PATH. Your environment seems to be" \
         "setup correctly. :-)"
  end
end

# Public: Install SBCL by running:
#
# INSTALL_ROOT=#{INSTALL_DESTINATION} sh ./install.sh
#
# Then copy output/scbl.core from SBCL dir to INSTALL_DESTINATION
def install_sbcl(version)
  puts
  puts "Installing to #{INSTALL_DESTINATION}"

  file_path = DOWNLOAD_DESTINATION + build_file_name(version)
  extracted_dir = file_path.sub('-binary.tar.bz2', '')

  # # SBCL_HOME conflicts with INSTALL_ROOT (for some odd reason)
  # sbcl_home           = ENV["SBCL_HOME"]
  # ENV['INSTALL_ROOT'] = INSTALL_DESTINATION

  # Dir.chdir extracted_dir
  # `unset SBCL_HOME && sh ./install.sh`
  # FileUtils.cp 'output/sbcl.core', INSTALL_DESTINATION
  # ENV['SBCL_HOME']    = sbcl_home

  sbcl_home           = ENV["SBCL_HOME"]

  # Update symlink
  `cd #{sbcl_home}; sudo ln -s #{extracted_dir} #{sbcl_home}`
end

# Public: Extract the tarball in DOWNLOAD_DESTINATION
def extract_tarball(version)
  file_path = DOWNLOAD_DESTINATION + build_file_name(version)

  puts
  puts "Extracting #{file_path}"

  Dir.chdir DOWNLOAD_DESTINATION
  Archive.new(file_path).extract
end

def get_current_version
  `sbcl --version`.split[1]
end

def get_latest_version_string(versions)
  versions.each { |version|
    version = version[0..-2]
    filename = build_file_name version
    file_url = build_download_url version

    puts "Checking version #{version}"
    puts "    Filename: #{filename}"
    puts "    File URL: #{file_url}"
    puts "    Exists?: #{url_exists? file_url}"

    return version if url_exists? file_url
  }
  ""
end

def build_download_url(version)
  filename = build_file_name version
  SBCL_DOWNLOAD_URL + version + "/" + filename
end

def build_file_name(version)
  SBCL_TARBALL_FORMAT % { :version => version }
end

def url_exists?(url)
  url = URI.parse url
  return_code = Net::HTTP.new(url.host, url.port).request_head(url.path).code
  nil != ((/3../ =~ return_code) || (/2../ =~ return_code))
end

# Public: Download latest version to DOWNLOAD_DESTINATION
def download_latest(version)
  filename = build_file_name version
  file_url_path = SITE_PATH + version + "/" + filename

  # puts "Filename: #{filename}"
  # puts "File URL: #{build_download_url version}"

  download_and_display(SITE_NAME,
                       file_url_path,
                       "#{DOWNLOAD_DESTINATION}/#{filename}")
end

# Public: Get all version strings from SBCL download URL
def get_version_strings
  doc = Nokogiri::HTML open(SBCL_DOWNLOAD_URL)
  version_strings = doc.css("img[alt='[DIR]'] + a")[1..-1].map {|e| e.content}.reverse
end

class Fixnum
  def format_number
    self.to_s.reverse.gsub(/...(?=.)/,'\&,').reverse
  end
end

def download(server, path, destination = "/tmp/somefile")
  Thread.new do
    thread          = Thread.current
    thread[:done]   = 0

    Net::HTTP.start(server) do |http|
      open(destination, 'wb') do |file|
        http.request_get(path) do |resp|
          thread[:total] = resp['Content-Length'].to_i

          if thread[:total] == 0
            puts "File not found!"
            thread.terminate
          end

          puts "File size: #{thread[:total].format_number} B"

          resp.read_body do |segment|
            file.write segment

            thread[:done] += segment.length
            thread[:progress] = thread[:done].quo(thread[:total]) * 100
          end
        end
      end
    end
  end
end

# Public: Download a file from a server, return true if the file exists and
# false vice-versa.
def download_and_display(server, path, destination = "/tmp/somefile")
  thread = download server, path, destination
  puts "Prepare to download: #{server}/#{path}"

  while !thread.join(1)
    progress = thread[:progress].to_f
    print "Downloading: \t%{done}/%{total} \t\t%{progress}\r" % {
      :done      => thread[:done].format_number,
      :total     => thread[:total].format_number,
      :progress  => "%0.2f%%" % progress
    } if progress != 0
  end

  puts
  puts "%{total}/%{total}\t\t\t100%" % {
    :total     => thread[:total].format_number,
  }
  puts "Done!"
  thread[:total] != 0
end

#####
## Main
#

main

----

== License

Unless clearly stated, do whatever you want with them.  If you like it, buy me
a good strong coffee :-).

== Description

* `prefix [text]` - Reads text from stdin an prefix all lines with
  `text`. `text` is set to `# ` by default. In Rc shell.

* `i3-exec-command` - Execute an i3 command in [i3 window
  manager](http://i3wm.org/), in SH.

* `i3-switch-window` - Task switcher for
  [i3 window manager](http://i3wm.org/), in Python using `dzen`.

* `i3-move-to-workspace` - Move a window to a workspace in i3 window manager,
  in SH.

* `i3-to-workspace` - Switch to a workspace in i3 window manager, in SH.

* `i3-rename-workspace` - Rename a workspace in i3 window manager, in SH.

* `update-sbcl` - Check and update [SBCL](http://www.sbcl.org/), in Ruby.

* `rename-urt-demos` - Rename Urban Terror 4.1 demo files (upcase, reformat
  for better timestamp and map), in Python.

* `get-monitors` - Get `output mode rate` for all active monitors using
  `xrandr`, in Ruby.

* `github-repo-to-ssh` - Convert `git@` protocol to `git+ssh` which Mercurial
  understands, in Ruby.

* `set-default-monitor-config` - Basic multihead, in Ruby.

* `du-this` - Get disk usage for all files and directories residing in the
  current directory and sort them in descending order, in SH.

* `monitor-off` - Turn off monitor, in SH.

* `show-cpu-temp` - Show my laptap's 2 CPUs temperature, in SH.

* `run-ibus-daemon` - Run/restart iBus daemon, with Xim support, in SH.

* `run-xiki` - Fresh start Xiki (due to a bug at startup, Xiki needs to
  restart after the first run), in SH.

* `run-zsnes` - Run Zsnes emulator, in SH.

* `git-rm-orphaned` - Remove deleted files from Git cache, in SH.

* `firefox-beta` - Run Firefox beta, in SH.

* `firefox-beta-new-instance` - Run new instance of Firefox beta (Firefox is
  called with `no-remote`), in SH.

* `python-print-site-packages-path` - Print Python site packages path, in SH.

* `intel-adjust-brightness` - Adjust brightness with shell script, requires
  `ALL=NOPASSWD: /usr/bin/tee` in your `/etc/sudoers` (edited by `visudo`), in
  SH.

* `virtualenv-symlink` - Symlink Python
  [virtualenv](https://virtualenv.pypa.io/en/latest/), in SH.

* `count-monitors` - Count number of connected monitors, in SH.

* `extract-audio` - Extract from a video file, creating the same file name
  with appropriate extension, in SH with FFmpeg.

* `update-openjdk-8-font-patched` - Update OpenJDK 8 with font rendering patch
  from PPA
  [no1wantdthisname](https://launchpad.net/~no1wantdthisname/+archive/ubuntu/openjdk-fontfix),
  in [Rc shell](http://plan9.bell-labs.com/sys/doc/rc.html).

* `local-port-open-p <port>` - Check if a local port is open, returning 0 if it is
  and 1 otherwise, in SH.

* `sbcl-cmpitg-slime <port> ...` - Start a SBCL Slime on a bunch of ports with
  Tmux; if called with no argument, use port 4005, in Rc shell.

* `format-text` (env var: `column`) - Format text with
  [par](http://www.nicemice.net/par/); column width is set by `column`
  environment variable; by default `column` is `78`, in Rc shell.

* `emacs-format-text` - Format text with Emacs (batch mode) width column width
  78 (TODO: customizable), in Rc shell, requires Emacs.
